services:
  client:
    image: "rupeshbiswas/multi-client"
    hostname: client

  server:
    image: "rupeshbiswas/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: "rupeshbiswas/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: "rupeshbiswas/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
